volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:lts
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      # solves security issues of nextloud
      - TRUSTED_PROXIES=172.22.0.0/24
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.otasovo.cz
      - OVERWRITEHOST=nextcloud.otasovo.cz
      - OVERWRITEPROTOCOL=https
      - OVERWRITECLIURL=https://nextcloud.otasovo.cz
    env_file:
      - .env
    labels:
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.otasovo.cz`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=default"

#      # solves security issues of nextloud
##      - "traefik.http.middlewares.nextcloud.headers.framedeny=true"
##      - "traefik.http.middlewares.nextcloud.headers.browserxssfilter=true"
#
##      - "traefik.http.routers.nextcloud.middlewares=servicests,nextcloud-dav"

      # Solves Security & setup warning:
      # Some headers are not set correctly on your instance - The `Strict-Transport-Security` HTTP header is not set
      # (should be at least `15552000` seconds). For enhanced security, it is recommended to enable HSTS.
      # For more details see the documentation ↗.
      - "traefik.http.routers.nextcloud.middlewares=servicests"
      - "traefik.http.middlewares.servicests.headers.stspreload=true"
      - "traefik.http.middlewares.servicests.headers.stsseconds=31536000"
#
## new nextcloud works fine without it
##      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
##      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"

  cron:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db