volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:lts
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - .env
    labels:
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.otasovo.cz`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=default"

      # Solves Security & setup warning:
      # Some headers are not set correctly on your instance - The `Strict-Transport-Security` HTTP header is not set
      # (should be at least `15552000` seconds). For enhanced security, it is recommended to enable HSTS.
      # For more details see the documentation ↗.
      - "traefik.http.routers.nextcloud.middlewares=servicests"
      - "traefik.http.middlewares.servicests.headers.stspreload=true"
      - "traefik.http.middlewares.servicests.headers.stsseconds=31536000"

  cron:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db